name: deploy netflix landing page 

on :
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  delpoy:
    runs-on: ubuntu_latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Deplot to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./"
          production-deploy: true
          deploy-message: "Netfliz page deployment from github actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID}}
          
          
